## WiSHFUL Agent config file

agent_info:
  name: 'agent_123'
  info: 'agent_info'
  iface: 'eno1'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"eno1", "groupName":"wishful_1234"}

  simple:
      module : wishful_module_spectral_scan_usrp
      class_name : SpectralScanUsrpModule
      interfaces : ['eno2']

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule

##  rule_manager:
##      module : wishful_module_rules
##      class_name : RuleManagerModule
