## WiSHFUL Controller's config file

controller:
    name: "Controller"
    info: "WiSHFUL Controller"
    dl: "tcp://10.11.17.9:8990"
    ul: "tcp://10.11.17.9:8989"

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryControllerModule
        kwargs: {"iface":"eno1", "groupName":"wishful_1234", "downlink":"tcp://10.11.17.9:8990", "uplink":"tcp://10.11.17.9:8989"}
